apiVersion: v1
kind: Service
metadata:
  name: sentiment-svc
  namespace: pj
  labels:
    app: sentiment-app
spec:
  type: LoadBalancer
  selector:
    app: sentiment-app
  ports:
    - name: http
      port: 80
      targetPort: 8080
