apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sentiment-monitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: sentiment-app
  namespaceSelector:
    matchNames:
      - pj
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
